name: Deploy Frontend

on:
  push:
    branches: [ "main" ] # Hoặc main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # 1. Vào thư mục Frontend để lấy code mới
            cd ${{ secrets.FRONTEND_PATH }}
            git fetch origin dev
            git reset --hard origin/dev
            
            # 2. Di chuyển sang thư mục Backend (nơi chứa docker-compose.yml)
            cd ${{ secrets.BACKEND_PATH }}
            
            # 3. Ra lệnh Build lại service Frontend
            # Docker compose sẽ nhìn sang folder frontend (nhờ config ../) để lấy code mới vừa pull
            docker compose -p cogni-stream up -d --build cogni-stream-frontend
            
            # 4. Dọn dẹp
            docker image prune -f
